export const FETCH_BOQ_REQUEST = 'FETCH_BOQ_REQUEST';
export const FETCH_BOQ_SUCCESS = 'FETCH_BOQ_SUCCESS';
export const FETCH_BOQ_FAILURE = 'FETCH_BOQ_FAILURE';

export const FETCH_MATERIAL_REQUEST = 'FETCH_MATERIAL_REQUEST';
export const FETCH_MATERIAL_SUCCESS = 'FETCH_MATERIAL_SUCCESS';
export const FETCH_MATERIAL_FAILURE = 'FETCH_MATERIAL_FAILURE';

export const FETCH_LABOUR_REQUEST = 'FETCH_LABOUR_REQUEST';
export const FETCH_LABOUR_SUCCESS = 'FETCH_LABOUR_SUCCESS';
export const FETCH_LABOUR_FAILURE = 'FETCH_LABOUR_FAILURE';

export const FETCH_MACHINERY_REQUEST = 'FETCH_MACHINERY_REQUEST';
export const FETCH_MACHINERY_SUCCESS = 'FETCH_MACHINERY_SUCCESS';
export const FETCH_MACHINERY_FAILURE = 'FETCH_MACHINERY_FAILURE';
