export const FETCH_BOQ_REQUEST = 'FETCH_BOQ_REQUEST';
export const FETCH_BOQ_SUCCESS = 'FETCH_BOQ_SUCCESS';
export const FETCH_BOQ_FAILURE = 'FETCH_BOQ_FAILURE';

export const FETCH_MATERIAL_REQUEST = 'FETCH_MATERIAL_REQUEST';
export const FETCH_MATERIAL_SUCCESS = 'FETCH_MATERIAL_SUCCESS';
export const FETCH_MATERIAL_FAILURE = 'FETCH_MATERIAL_FAILURE';

export const FETCH_LABOUR_REQUEST = 'FETCH_LABOUR_REQUEST';
export const FETCH_LABOUR_SUCCESS = 'FETCH_LABOUR_SUCCESS';
export const FETCH_LABOUR_FAILURE = 'FETCH_LABOUR_FAILURE';

export const FETCH_MACHINERY_REQUEST = 'FETCH_MACHINERY_REQUEST';
export const FETCH_MACHINERY_SUCCESS = 'FETCH_MACHINERY_SUCCESS';
export const FETCH_MACHINERY_FAILURE = 'FETCH_MACHINERY_FAILURE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const CREATE_WORK_SUMMARY_REQUEST = 'CREATE_WORK_SUMMARY_REQUEST';
export const CREATE_WORK_SUMMARY_SUCCESS = 'CREATE_WORK_SUMMARY_SUCCESS';
export const CREATE_WORK_SUMMARY_FAILURE = 'CREATE_WORK_SUMMARY_FAILURE';

export const FETCH_WORK_ITEM_REQUEST = 'FETCH_WORK_ITEM_REQUEST';
export const FETCH_WORK_ITEM_SUCCESS = 'FETCH_WORK_ITEM_SUCCESS';
export const FETCH_WORK_ITEM_FAILURE = 'FETCH_WORK_ITEM_FAILURE';